# $FreeBSD: release/9.0.0/lib/clang/libllvmx86info/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo/
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS=	X86GenInstrInfo \
	X86GenRegisterInfo \
	X86GenSubtargetInfo

.include "../clang.lib.mk"
