#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: release/9.0.0/usr.bin/ktrace/Makefile 201386 2010-01-02 10:27:05Z ed $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

WARNS?=	4

.include <bsd.prog.mk>
