# $FreeBSD: release/9.0.0/lib/clang/libllvmx86asmparser/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmx86asmparser

SRCDIR=	lib/Target/X86/AsmParser
INCDIR=	lib/Target/X86
SRCS=	X86AsmLexer.cpp \
	X86AsmParser.cpp

TGHDRS=	X86GenAsmMatcher \
	X86GenInstrInfo \
	X86GenRegisterInfo \
	X86GenSubtargetInfo

.include "../clang.lib.mk"
