# $FreeBSD: release/9.0.0/lib/clang/libllvmtarget/Makefile 226890 2011-10-28 21:08:39Z dim $

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Mangler.cpp \
	Target.cpp \
	TargetData.cpp \
	TargetELFWriterInfo.cpp \
	TargetFrameLowering.cpp \
	TargetInstrInfo.cpp \
	TargetLibraryInfo.cpp \
	TargetLoweringObjectFile.cpp \
	TargetMachine.cpp \
	TargetRegisterInfo.cpp \
	TargetSubtargetInfo.cpp

.include "../clang.lib.mk"
