# $FreeBSD: release/9.0.0/usr.sbin/bsdinstall/distfetch/Makefile 218799 2011-02-18 14:54:34Z nwhitehorn $

BINDIR= /usr/libexec/bsdinstall
PROG=	distfetch
LDADD=	-lfetch -lncursesw -ldialog -lm

WARNS?=	6
NO_MAN=	true

.include <bsd.prog.mk>
