# $FreeBSD: release/9.0.0/lib/clang/libllvmipa/Makefile 210299 2010-07-20 17:16:57Z ed $

LIB=	llvmipa

SRCDIR=	lib/Analysis/IPA
SRCS=	CallGraph.cpp \
	CallGraphSCCPass.cpp \
	FindUsedTypes.cpp \
	GlobalsModRef.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
