# $FreeBSD: release/9.0.0/usr.sbin/boot0cfg/Makefile 204352 2010-02-26 09:41:16Z ru $

PROG=	boot0cfg
MAN=	boot0cfg.8

DPADD=	${LIBGEOM} ${LIBBSDXML} ${LIBSBUF}
LDADD=	-lgeom -lbsdxml -lsbuf

.include <bsd.prog.mk>
