# $FreeBSD: release/9.0.0/sys/modules/ata/atapci/chipsets/atavia/Makefile 183724 2008-10-09 12:56:57Z sos $

.PATH: ${.CURDIR}/../../../../../dev/ata/chipsets

KMOD=	atavia
SRCS=	ata-via.c
SRCS+=  opt_ata.h ata_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>

