# $FreeBSD: release/9.0.0/lib/clang/libclangdriver/Makefile 210299 2010-07-20 17:16:57Z ed $

LIB=	clangdriver

SRCDIR=	tools/clang/lib/Driver
SRCS=	Action.cpp \
	Arg.cpp \
	ArgList.cpp \
	CC1AsOptions.cpp \
	CC1Options.cpp \
	Compilation.cpp \
	Driver.cpp \
	DriverOptions.cpp \
	HostInfo.cpp \
	Job.cpp \
	OptTable.cpp \
	Option.cpp \
	Phases.cpp \
	Tool.cpp \
	ToolChain.cpp \
	ToolChains.cpp \
	Tools.cpp \
	Types.cpp

TGHDRS=	CC1AsOptions \
	CC1Options \
	DiagnosticCommonKinds \
	DiagnosticDriverKinds \
	Options

.include "../clang.lib.mk"
