# $FreeBSD: release/9.0.0/sys/modules/drm/Makefile 203288 2010-01-31 14:30:39Z rnoland $

SUBDIR = \
	drm \
	i915 \
	mach64 \
	mga \
	r128 \
	radeon \
	savage \
	sis \
	tdfx \
	via

.include <bsd.subdir.mk>
