# $FreeBSD: release/9.0.0/lib/clang/libllvmmcparser/Makefile 226890 2011-10-28 21:08:39Z dim $

LIB=	llvmmcparser

SRCDIR=	lib/MC/MCParser
SRCS=	AsmLexer.cpp \
	AsmParser.cpp \
	COFFAsmParser.cpp \
	DarwinAsmParser.cpp \
	ELFAsmParser.cpp \
	MCAsmLexer.cpp \
	MCAsmParser.cpp \
	MCAsmParserExtension.cpp \
	MCTargetAsmParser.cpp

.include "../clang.lib.mk"
