# $FreeBSD: release/9.0.0/lib/clang/libllvmmipsinfo/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo/
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS=	MipsGenInstrInfo \
	MipsGenRegisterInfo \
	MipsGenSubtargetInfo

.include "../clang.lib.mk"
