#!/bin/sh
#
# Add additional swap files
#
# $FreeBSD: release/9.0.0/etc/rc.d/addswap 197139 2009-09-12 22:13:41Z hrs $
#

# PROVIDE: addswap
# REQUIRE: FILESYSTEMS
# KEYWORD: nojail

. /etc/rc.subr

name="addswap"
start_cmd="addswap_start"
stop_cmd=":"

addswap_start()
{
	case ${swapfile} in
	[Nn][Oo] | '')
		;;
	*)
		if [ -w "${swapfile}" ]; then
			echo "Adding ${swapfile} as additional swap"
			mdev=`mdconfig -a -t vnode -f ${swapfile}` && swapon /dev/${mdev}
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
