#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/apmd 180564 2008-07-16 19:50:29Z dougb $
#

# PROVIDE: apmd
# REQUIRE: DAEMON apm
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="apmd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
start_precmd="apmd_prestart"

apmd_prestart()
{
	case `${SYSCTL_N} hw.machine_arch` in
	i386)
		# Enable apm if it is not already enabled
		if ! checkyesno apm_enable  && \
		    ! /etc/rc.d/apm forcestatus 1>/dev/null 2>&1
		then
			force_depend apm || return 1
		fi

		# Warn user about acpi apm compatibility support which
		# does not work with apmd.
		if [ ! -e /dev/apmctl ]; then
		    warn "/dev/apmctl not found; kernel is missing apm(4)"
		fi
		;;
	*)
		return 1
		;;
	esac
	return 0
}

load_rc_config $name
run_rc_command "$1"
