#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/ftp-proxy 180564 2008-07-16 19:50:29Z dougb $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar=`set_rcvar`
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
