#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/pppoed 180563 2008-07-16 19:22:48Z dougb $
#

# PROVIDE: pppoed
# REQUIRE: NETWORKING
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="pppoed"
rcvar="`set_rcvar`"
start_cmd="pppoed_start"
# XXX stop_cmd will not be straightforward
stop_cmd=":"

pppoed_start()
{
	local _opts

	if [ -n "${pppoed_provider}" ]; then
			pppoed_flags="${pppoed_flags} -p ${pppoed_provider}"
	fi
	echo 'Starting pppoed'
	_opts=$-; set -f
	/usr/libexec/pppoed ${pppoed_flags} ${pppoed_interface}
	set +f; set -${_opts}
}

load_rc_config $name
run_rc_command "$1"
