#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/rarpd 174438 2007-12-08 07:20:23Z dougb $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON cleanvar
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rarpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ethers"

load_rc_config $name
run_rc_command "$1"
