#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/timed 180564 2008-07-16 19:50:29Z dougb $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
