# $FreeBSD: release/9.0.0/lib/clang/libllvmpowerpcinstprinter/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmpowerpcinstprinter

SRCDIR=	lib/Target/PowerPC/InstPrinter
INCDIR=	lib/Target/PowerPC
SRCS=	PPCInstPrinter.cpp

TGHDRS=	PPCGenAsmWriter \
	PPCGenInstrInfo \
	PPCGenRegisterInfo \
	PPCGenSubtargetInfo

.include "../clang.lib.mk"
