# $FreeBSD: release/9.0.0/sys/powerpc/conf/Makefile 211483 2010-08-19 03:19:26Z nwhitehorn $

TARGET=powerpc
.if ${MACHINE_ARCH} == powerpc || ${MACHINE_ARCH} == powerpc64
TARGET_ARCH?=${MACHINE_ARCH}
.endif

.include "${.CURDIR}/../../conf/makeLINT.mk"
