#$FreeBSD: release/9.0.0/sys/modules/mxge/mxge/Makefile 194743 2009-06-23 17:42:06Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge

KMOD=	if_mxge
SRCS=	if_mxge.c mxge_lro.c device_if.h bus_if.h pci_if.h opt_inet.h

.include <bsd.kmod.mk>
