# $FreeBSD: release/9.0.0/lib/clang/libllvmx86disassembler/Makefile 226890 2011-10-28 21:08:39Z dim $

LIB=	llvmx86disassembler

SRCDIR=	lib/Target/X86/Disassembler
INCDIR=	lib/Target/X86
SRCS=	X86Disassembler.cpp

TGHDRS=	X86GenDisassemblerTables \
	X86GenEDInfo \
	X86GenInstrInfo \
	X86GenRegisterInfo

.include "../clang.lib.mk"
