# $FreeBSD: release/9.0.0/lib/clang/libllvmbitreader/Makefile 212904 2010-09-20 16:43:17Z dim $

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitcodeReader.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
