#	$ANA: Makefile,v 1.1.1.1 1996/09/25 21:12:57 wollman Exp $
# $FreeBSD: release/9.0.0/usr.sbin/pciconf/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	pciconf
SRCS=	pciconf.c cap.c
MAN=	pciconf.8

CFLAGS+= -I${.CURDIR}/../../sys

WARNS?=	3

.include <bsd.prog.mk>
