# $FreeBSD: release/9.0.0/lib/clang/libllvmarminfo/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo/
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS=	ARMGenInstrInfo \
	ARMGenRegisterInfo \
	ARMGenSubtargetInfo

.include "../clang.lib.mk"
