# $FreeBSD: release/9.0.0/lib/clang/libllvminstrumentation/Makefile 221345 2011-05-02 21:04:37Z dim $

LIB=	llvminstrumentation

SRCDIR=	lib/Transforms/Instrumentation
SRCS=	EdgeProfiling.cpp \
	GCOVProfiling.cpp \
	Instrumentation.cpp \
	OptimalEdgeProfiling.cpp \
	PathProfiling.cpp \
	ProfilingUtils.cpp \

#TGHDRS=	Intrinsics

.include "../clang.lib.mk"
