# $FreeBSD: release/9.0.0/sys/modules/bwn/Makefile 203945 2010-02-16 01:44:14Z weongyo $

.PATH: ${.CURDIR}/../../dev/bwn

KMOD=	if_bwn
SRCS=	if_bwn.c if_bwnreg.h if_bwnvar.h
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
