# $FreeBSD: release/9.0.0/lib/clang/libllvmarminstprinter/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmarminstprinter

SRCDIR=	lib/Target/ARM/InstPrinter
INCDIR=	lib/Target/ARM
SRCS=	ARMInstPrinter.cpp

TGHDRS=	ARMGenAsmWriter \
	ARMGenInstrInfo \
	ARMGenRegisterInfo \
	ARMGenSubtargetInfo

.include "../clang.lib.mk"
