#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/bootparams 174438 2007-12-08 07:20:23Z dougb $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar=`set_rcvar`
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
