#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/ftpd 180564 2008-07-16 19:50:29Z dougb $
#

# PROVIDE: ftpd
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpd"
rcvar=`set_rcvar`
command="/usr/libexec/${name}"
pidfile="/var/run/${name}.pid"
start_precmd=ftpd_prestart

ftpd_prestart()
{
	rc_flags="-D ${rc_flags}"
	return 0
}

load_rc_config $name
run_rc_command "$1"
