#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/rtsold 204427 2010-02-27 19:02:21Z ume $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rtsold"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
