#!/bin/sh
#
# $FreeBSD: release/9.0.0/etc/rc.d/sdpd 180564 2008-07-16 19:50:29Z dougb $
#

# PROVIDE: sdpd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="sdpd"
command="/usr/sbin/${name}"
rcvar=`set_rcvar`
required_modules="ng_btsocket"

load_rc_config $name
control="${sdpd_control:-/var/run/sdp}"
group="${sdpd_groupname:-nobody}"
user="${sdpd_username:-nobody}"
command_args="-c ${control} -g ${group} -u ${user}"

run_rc_command "$1"
