# $FreeBSD: release/9.0.0/lib/clang/libclanglex/Makefile 218893 2011-02-20 19:33:47Z dim $

LIB=	clanglex

SRCDIR=	tools/clang/lib/Lex
SRCS=	HeaderMap.cpp \
	HeaderSearch.cpp \
	Lexer.cpp \
	LiteralSupport.cpp \
	MacroArgs.cpp \
	MacroInfo.cpp \
	PPCaching.cpp \
	PPDirectives.cpp \
	PPExpressions.cpp \
	PPLexerChange.cpp \
	PPMacroExpansion.cpp \
	PTHLexer.cpp \
	Pragma.cpp \
	PreprocessingRecord.cpp \
	Preprocessor.cpp \
	PreprocessorLexer.cpp \
	ScratchBuffer.cpp \
	TokenConcatenation.cpp \
	TokenLexer.cpp

TGHDRS=	AttrSpellings \
	DiagnosticCommonKinds \
	DiagnosticLexKinds

.include "../clang.lib.mk"
