# $FreeBSD: release/9.0.0/lib/clang/libllvmasmparser/Makefile 210299 2010-07-20 17:16:57Z ed $

LIB=	llvmasmparser

SRCDIR=	lib/AsmParser
SRCS=	LLLexer.cpp \
	LLParser.cpp \
	Parser.cpp

.include "../clang.lib.mk"
