# $FreeBSD: release/9.0.0/lib/clang/libllvmpowerpcinfo/Makefile 224145 2011-07-17 19:51:40Z dim $

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo/
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS=	PPCGenInstrInfo \
	PPCGenRegisterInfo \
	PPCGenSubtargetInfo

.include "../clang.lib.mk"
