# $FreeBSD: release/9.0.0/lib/clang/libclangindex/Makefile 212904 2010-09-20 16:43:17Z dim $

LIB=	clangindex

SRCDIR=	tools/clang/lib/Index
SRCS=	ASTLocation.cpp \
	Analyzer.cpp \
	CallGraph.cpp \
	DeclReferenceMap.cpp \
	Entity.cpp \
	GlobalSelector.cpp \
	Handlers.cpp \
	IndexProvider.cpp \
	Indexer.cpp \
	Program.cpp \
	SelectorMap.cpp \

TGHDRS=	AttrList \
	Attrs \
	DeclNodes \
	DiagnosticCommonKinds \
	StmtNodes

.include "../clang.lib.mk"
