# $FreeBSD: release/9.0.0/lib/clang/libllvmscalaropts/Makefile 226890 2011-10-28 21:08:39Z dim $

LIB=	llvmscalaropts

SRCDIR=	lib/Transforms/Scalar
SRCS=	ADCE.cpp \
	BasicBlockPlacement.cpp \
	CodeGenPrepare.cpp \
	ConstantProp.cpp \
	CorrelatedValuePropagation.cpp \
	DCE.cpp \
	DeadStoreElimination.cpp \
	EarlyCSE.cpp \
	GVN.cpp \
	IndVarSimplify.cpp \
	JumpThreading.cpp \
	LICM.cpp \
	LoopDeletion.cpp \
	LoopIdiomRecognize.cpp \
	LoopRotation.cpp \
	LoopStrengthReduce.cpp \
	LoopUnrollPass.cpp \
	LoopUnswitch.cpp \
	MemCpyOptimizer.cpp \
	ObjCARC.cpp \
	Reassociate.cpp \
	SCCP.cpp \
	ScalarReplAggregates.cpp \
	SimplifyCFGPass.cpp \
	SimplifyLibCalls.cpp \
	Sink.cpp \
	TailRecursionElimination.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
