# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: release/9.0.0/sbin/routed/rtquery/Makefile 204405 2010-02-27 10:17:27Z uqs $

PROG=	rtquery
MAN=	rtquery.8
LDADD=	-lmd
DPADD=	${LIBMD}
WARNS?=	3

.include <bsd.prog.mk>
