# $FreeBSD: release/9.0.0/lib/clang/libllvmbitwriter/Makefile 212904 2010-09-20 16:43:17Z dim $

LIB=	llvmbitwriter

SRCDIR=	lib/Bitcode/Writer
SRCS=	BitcodeWriter.cpp \
	BitcodeWriterPass.cpp \
	ValueEnumerator.cpp

.include "../clang.lib.mk"
