# $FreeBSD: release/9.0.0/sys/modules/wpi/Makefile 177671 2008-03-27 20:38:03Z antoine $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
