# $FreeBSD: release/9.0.0/lib/clang/libllvmtablegen/Makefile 226633 2011-10-22 14:08:43Z dim $

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	TableGenBackend.cpp \
	TGLexer.cpp \
	TGParser.cpp
LLVM_REQUIRES_EH=

.include "../clang.lib.mk"
