#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/9.0.0/share/misc/Makefile 174763 2007-12-19 01:28:17Z imp $

.PATH:	${.CURDIR}/../../sys/dev/usb

FILES=	ascii birthtoken bsd-family-tree committers-doc.dot committers-ports.dot \
	committers-src.dot eqnchar flowers init.ee \
	iso3166 iso639 latin1 man.template mdoc.template operator pci_vendors \
	scsi_modes usb_hid_usages usbdevs

NO_OBJ=
FILESDIR=	${BINDIR}/misc

.include <bsd.prog.mk>
