# $FreeBSD: release/9.0.0/lib/clang/libllvmx86utils/Makefile 218893 2011-02-20 19:33:47Z dim $

LIB=	llvmx86utils

SRCDIR=	lib/Target/X86/Utils
INCDIR=	lib/Target/X86
SRCS=	X86ShuffleDecode.cpp

.include "../clang.lib.mk"
