# Copyright (c) 2011 David E O'Brien
# $FreeBSD: release/9.0.0/lib/libedit/edit/readline/Makefile 220370 2011-04-05 18:41:01Z obrien $

INCS=	readline.h history.h

INCSDIR= ${INCLUDEDIR}/edit/readline

.include <bsd.lib.mk>
