# $FreeBSD: release/9.0.0/usr.sbin/bsdinstall/scripts/Makefile 223897 2011-07-09 23:01:54Z nwhitehorn $

SCRIPTS= auto adduser checksum config docsinstall hostname jail keymap \
	 mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 rootpass \
	 services time umount wlanconfig
BINDIR= /usr/libexec/bsdinstall

NO_MAN=	true

.include <bsd.prog.mk>
